# Simulation Parameters
N: 100
dt: 0.1

# System Parameters
n_states: 14
n_controls: 6
gravity_vector: [0.0, 0.0, -3.711]  # Mars gravity in m/s^2
standard_gravity: 9.80665           # Standard gravity in m/s^2
I_sp: 300.0                         # Specific impulse in seconds
inertia_matrix:                     # Inertia matrix in kg·m²
  - [5000.0, 0.0, 0.0]
  - [0.0, 5000.0, 0.0]
  - [0.0, 0.0, 5000.0]

# Initial Conditions
x0:
  - 0.0        # Position x
  - 0.0        # Position y
  - 1000.0     # Position z
  - 0.0        # Velocity x
  - 0.0        # Velocity y
  - -50.0      # Velocity z
  - 1.0        # Quaternion q0
  - 0.0        # Quaternion q1
  - 0.0        # Quaternion q2
  - 0.0        # Quaternion q3
  - 0.0        # Angular velocity ωx
  - 0.0        # Angular velocity ωy
  - 0.0        # Angular velocity ωz
  - 5000.0     # Mass

# Control Input Guess
u_guess:
  - 0.0        # Thrust Fx
  - 0.0        # Thrust Fy
  - 49050.0    # Thrust Fz
  - 0.0        # Moment Mx
  - 0.0        # Moment My
  - 0.0        # Moment Mz
