# Simulation Parameters
N: 30
dt: 0.1
sigma: 15.0 # TODO: put real number
# System Parameters
n_states: 14
n_controls: 3
#gravity_vector: [0.0, 0.0, -3.711]  # Mars gravity in m/s^2
gravity_vector: [0.0, 0.0, -9.80665]  # Mars gravity in m/s^2
standard_gravity: 9.80665           # Standard gravity in m/s^2
I_sp: 300.0                         # Specific impulse in seconds
# inertia_matrix:                     # Inertia matrix in kg·m²
#   - [5000.0, 0.0, 0.0]
#   - [0.0, 5000.0, 0.0]
#   - [0.0, 0.0, 5000.0]
inertia_matrix:                     # Inertia matrix in kg·m²
  - [4000000.0, 0.0, 0.0]
  - [0.0, 4000000.0, 0.0]
  - [0.0, 0.0, 100000.0]

# Initial Conditions
x0:
  - 30000.0     # wet Mass
  - 0.0        # Position x
  - 200.0        # Position y
  - 200.0     # Position z
  - -50.0        # Velocity x
  - -100.0        # Velocity y
  - -50.0      # Velocity z
  - 1.0        # Quaternion q0
  - 0.0        # Quaternion q1
  - 0.0        # Quaternion q2
  - 0.0        # Quaternion q3
  - 0.0        # Angular velocity ωx
  - 0.0        # Angular velocity ωy
  - 0.0        # Angular velocity ωz

# # Final Conditions
# rf:
#   - 0.0        # Position x
#   - 0.0        # Position y
#   - 0.0        # Position z

# vf:
#   - 0.0        # Velocity x
#   - 0.0        # Velocity y
#   - -5.0        # Velocity z

# omegaf:
#   - 0.0        # Angular velocity ωx
#   - 0.0        # Angular velocity ωy
#   - 0.0        # Angular velocity ωz

# qf:
#   - 1.0        # Quaternion q0
#   - 0.0        # Quaternion q1
#   - 0.0        # Quaternion q2
#   - 0.0        # Quaternion q3

xf:
  - 22000.0     # dry Mass
  - 0.0        # Position x
  - 0.0        # Position y
  - 0.0        # Position z
  - 0.0        # Velocity x
  - 0.0        # Velocity y
  - -5.0        # Velocity z
  - 1.0        # Quaternion q0
  - 0.0        # Quaternion q1
  - 0.0        # Quaternion q2
  - 0.0        # Quaternion q3
  - 0.0        # Angular velocity ωx
  - 0.0        # Angular velocity ωy
  - 0.0        # Angular velocity ωz

# Control Input Guess
# u_guess:
#   - 0.0        # Thrust Fx
#   - 0.0        # Thrust Fy
#   - 49050.0    # Thrust Fz
#   - 0.0        # Moment Mx
#   - 0.0        # Moment My
#   - 0.0        # Moment Mz
u_guess:
  - 0.0        # Thrust Fx
  - 0.0        # Thrust Fy
  - 49050.0    # Thrust Fz

r_T_B: 
  - 0.0
  - 0.0    
  - -14.0   


# dry mass
m_dry: 22000.0
mass_index: 14
m_wet: 30000.0

# glide slope angle
gamma_gs: 20
tan_gamma_gs: 0.36397
#deg2rad(90.0)
theta_max: 70
cos_theta_max: 0.34202
delta_max: 7
tan_delta_max: 0.12278

omega_max: 90
rad_omega_max: 1.5708
#deg2rad(30.0)

T_max: 800000.0
T_min: 320000.0

max_iters: 20
tolerance: 1e-4

#TODO: put real number
weight_nu: 100000.0
weight_sigma: 10.0
tr_radius: 5.0